Numpy

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
# 1D array
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))#1 rows and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])


In [10]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]
