Numpy

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
# 1D array
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))#1 rows and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])


In [10]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


Using Inbuilt Functions to Create Arrays

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# identity_matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size ( Number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item Size ( In byte): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size ( Number of elements):  6
Data type:  int64
Item Size ( In byte):  8


In [ ]:
# Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise Addition
print("Addition : ",arr1+arr2)
# Element wise Substraction
print("Substraction : ",arr1-arr2)

print(arr1 * arr2)

print(arr1 / arr2)

Addition :  [11 22 33 44 55]
Substraction :  [ -9 -18 -27 -36 -45]


In [23]:
# Universal Function
arr = np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))
# exponential
print(np.exp(arr))
# sine
print(np.sin(arr))
# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
# Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)
arr[0]
arr[1][2]



Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(7)

In [30]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [33]:
# modify array
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Statistical Operations and Normalization

In [36]:
# Statistical concepts --Normalization
# to have a mean of 0 and standerd deviation  of 1

data = np.array([1, 2, 3, 4, 5])
# calculate the mean and standerd deviation
mean = np.mean(data)
std_dev = np.std(data)
# Normalize the date
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# mean
print(np.mean(arr))
# median
print(np.median(arr))
# standerd deviation
print(np.std(arr))
# variance
print(np.var(arr))

5.5
5.5
2.8722813232690143
8.25


In [38]:
# Logical operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
